# Numpy Practice 

In [1]:
import numpy as np

In [2]:
print('hello world')

hello world


In [5]:
arr=np.array([2,3,43,7],np.int8)

In [6]:
arr

array([ 2,  3, 43,  7], dtype=int8)

In [7]:
arr[3]

7

In [8]:
arr.shape

(4,)

In [9]:
arr.dtype

dtype('int8')

In [10]:
arr[3]=24

In [11]:
arr

array([ 2,  3, 43, 24], dtype=int8)

*Array Creation methods*

**Array Creation from other python structures**

In [12]:
listarray =np.array([[1,2,3],[4,5,6],[9,8,8]])

In [13]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 8]])

In [14]:
listarray.shape

(3, 3)

In [15]:
listarray.dtype

dtype('int32')

In [17]:
listarray.size

9

In [18]:
setarray=np.array({23,33,45})

In [19]:
setarray

array({33, 45, 23}, dtype=object)

**intrinsic numpy array creation objects**

In [20]:
zeros=np.zeros((2,5))

In [21]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
rng=np.arange(15)

In [23]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
lspace=np.linspace(1,5,9)

In [27]:
lspace

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [28]:
emp=np.empty((4,6))

In [29]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56602523e-307, 1.29060871e-306, 2.13620264e-306],
       [6.23053614e-307, 1.20161797e-306, 6.23058707e-307,
        8.45593934e-307, 9.34598246e-307, 6.23061763e-307],
       [7.56603881e-307, 1.11260416e-306, 9.34598247e-307,
        9.34613185e-307, 3.11525958e-307, 1.69118108e-306],
       [8.06632139e-308, 1.20160711e-306, 1.69119330e-306,
        1.33511562e-306, 1.24610383e-306, 1.37954579e-306]])

In [30]:
emp_like =np.empty_like(lspace)

In [31]:
emp_like

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [32]:
ide=np.identity(4)

In [33]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
arrr=np.arange(99)

In [36]:
arrr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
arrr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [39]:
arrr=arrr.ravel()

In [40]:
arrr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# Axis

In [42]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [43]:
ar=np.array(x)

In [44]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [45]:
ar.sum(axis=0)

array([12,  8,  9])

In [46]:
ar.sum(axis=1)

array([ 6, 15,  8])

*somemethods*

In [47]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [48]:
ar.flat

In [49]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [50]:
ar.ndim

2

In [51]:
ar.size

9

In [52]:
ar.nbytes

36

In [54]:
one = np.array([1,7,2,19])

In [55]:
one.argmax()

3

In [56]:
one.argmin()

0

In [57]:
one.argsort()

array([0, 2, 1, 3], dtype=int64)

In [58]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [59]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])